In [28]:
import graphlab
import math

In [29]:
#Load data
train = graphlab.SFrame.read_csv('train.csv', column_type_hints=[int,int,str,int,int,int,int,str,str])
test = graphlab.SFrame.read_csv('test.csv', column_type_hints=[int,int,int,str,int,int,str,str])
store = graphlab.SFrame.read_csv('store.csv')
store = store.fillna("CompetitionDistance", 0).fillna("CompetitionOpenSinceMonth", 0).fillna("CompetitionOpenSinceYear", 0).fillna("Promo2SinceWeek", 0).fillna("Promo2SinceYear", 0)

PROGRESS: Finished parsing file /Users/kanna/Sandbox/kaggle/rossmann_store_sales/train.csv
PROGRESS: Parsing completed. Parsed 1017209 lines in 1.28845 secs.
PROGRESS: Finished parsing file /Users/kanna/Sandbox/kaggle/rossmann_store_sales/test.csv
PROGRESS: Parsing completed. Parsed 41088 lines in 0.057242 secs.
PROGRESS: Finished parsing file /Users/kanna/Sandbox/kaggle/rossmann_store_sales/store.csv
PROGRESS: Parsing completed. Parsed 100 lines in 0.010533 secs.
------------------------------------------------------
Inferred types from first line of file as
column_type_hints=[int,str,str,int,int,int,int,int,int,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------
PROGRESS: Finished parsing file /Users/kanna/Sandbox/kaggle/rossmann_store_sales/store.csv
PROGRESS: Parsing completed. Parsed 1115 lines in 0.010668 secs.

In [30]:
train.head(5)

Columns:
	Store	int
	DayOfWeek	int
	Date	str
	Sales	int
	Customers	int
	Open	int
	Promo	int
	StateHoliday	str
	SchoolHoliday	str

Rows: 5

Data:
+-------+-----------+------------+-------+-----------+------+-------+--------------+
| Store | DayOfWeek |    Date    | Sales | Customers | Open | Promo | StateHoliday |
+-------+-----------+------------+-------+-----------+------+-------+--------------+
|   1   |     5     | 2015-07-31 |  5263 |    555    |  1   |   1   |      0       |
|   2   |     5     | 2015-07-31 |  6064 |    625    |  1   |   1   |      0       |
|   3   |     5     | 2015-07-31 |  8314 |    821    |  1   |   1   |      0       |
|   4   |     5     | 2015-07-31 | 13995 |    1498   |  1   |   1   |      0       |
|   5   |     5     | 2015-07-31 |  4822 |    559    |  1   |   1   |      0       |
+-------+-----------+------------+-------+-----------+------+-------+--------------+
+---------------+
| SchoolHoliday |
+---------------+
|       1       |
|       1       |
|       1       |
|       1       |
|       1       |
+---------------+
[5 rows x 9 columns]

In [33]:
train = train[train['Sales'] > 0]
train['logSales'] = train['Sales'].apply(lambda x: math.log(x))
train = train.join(store, on='Store', how='inner')
test = test.join(store, on='Store', how='inner')

In [34]:
train.head(5)

Columns:
	Store	int
	DayOfWeek	int
	Date	str
	Sales	int
	Customers	int
	Open	int
	Promo	int
	StateHoliday	str
	SchoolHoliday	str
	logSales	float
	StoreType	str
	Assortment	str
	CompetitionDistance	int
	CompetitionOpenSinceMonth	int
	CompetitionOpenSinceYear	int
	Promo2	int
	Promo2SinceWeek	int
	Promo2SinceYear	int
	PromoInterval	str
	StoreType.1	str
	Assortment.1	str
	CompetitionDistance.1	int
	CompetitionOpenSinceMonth.1	int
	CompetitionOpenSinceYear.1	int
	Promo2.1	int
	Promo2SinceWeek.1	int
	Promo2SinceYear.1	int
	PromoInterval.1	str

Rows: 5

Data:
+-------+-----------+------------+-------+-----------+------+-------+--------------+
| Store | DayOfWeek |    Date    | Sales | Customers | Open | Promo | StateHoliday |
+-------+-----------+------------+-------+-----------+------+-------+--------------+
|   1   |     5     | 2015-07-31 |  5263 |    555    |  1   |   1   |      0       |
|   2   |     5     | 2015-07-31 |  6064 |    625    |  1   |   1   |      0       |
|   3   |     5     | 2015-07-31 |  8314 |    821    |  1   |   1   |      0       |
|   4   |     5     | 2015-07-31 | 13995 |    1498   |  1   |   1   |      0       |
|   5   |     5     | 2015-07-31 |  4822 |    559    |  1   |   1   |      0       |
+-------+-----------+------------+-------+-----------+------+-------+--------------+
+---------------+---------------+-----------+------------+---------------------+
| SchoolHoliday |    logSales   | StoreType | Assortment | CompetitionDistance |
+---------------+---------------+-----------+------------+---------------------+
|       1       | 8.56845648535 |     c     |     a      |         1270        |
|       1       | 8.71012492732 |     a     |     a      |         570         |
|       1       | 9.02569611981 |     a     |     a      |        14130        |
|       1       | 9.54645540195 |     c     |     c      |         620         |
|       1       | 8.48094405874 |     a     |     a      |        29910        |
+---------------+---------------+-----------+------------+---------------------+
+---------------------------+--------------------------+--------+-----------------+
| CompetitionOpenSinceMonth | CompetitionOpenSinceYear | Promo2 | Promo2SinceWeek |
+---------------------------+--------------------------+--------+-----------------+
|             9             |           2008           |   0    |        0        |
|             11            |           2007           |   1    |        13       |
|             12            |           2006           |   1    |        14       |
|             9             |           2009           |   0    |        0        |
|             4             |           2015           |   0    |        0        |
+---------------------------+--------------------------+--------+-----------------+
+-----------------+-----------------+-------------+-----+
| Promo2SinceYear |  PromoInterval  | StoreType.1 | ... |
+-----------------+-----------------+-------------+-----+
|        0        |                 |      c      | ... |
|       2010      | Jan,Apr,Jul,Oct |      a      | ... |
|       2011      | Jan,Apr,Jul,Oct |      a      | ... |
|        0        |                 |      c      | ... |
|        0        |                 |      a      | ... |
+-----------------+-----------------+-------------+-----+
[5 rows x 28 columns]

In [35]:
# Add new features from the Date variable
train['Date'] = train['Date'].str_to_datetime()
train = train.split_datetime('Date',limit=['year', 'month', 'day'])
print train.head(1)
test['Date'] = test['Date'].str_to_datetime()
test = test.split_datetime('Date',limit=['year', 'month', 'day'])
print test.head(1)

+-------+-----------+-------+-----------+------+-------+--------------+---------------+
| Store | DayOfWeek | Sales | Customers | Open | Promo | StateHoliday | SchoolHoliday |
+-------+-----------+-------+-----------+------+-------+--------------+---------------+
|   1   |     5     |  5263 |    555    |  1   |   1   |      0       |       1       |
+-------+-----------+-------+-----------+------+-------+--------------+---------------+
+---------------+-----------+------------+---------------------+---------------------------+
|    logSales   | StoreType | Assortment | CompetitionDistance | CompetitionOpenSinceMonth |
+---------------+-----------+------------+---------------------+---------------------------+
| 8.56845648535 |     c     |     a      |         1270        |             9             |
+---------------+-----------+------------+---------------------+---------------------------+
+--------------------------+--------+-----------------+-----------------+---------------+
| CompetitionOpenSinceYear | Promo2 | Promo2SinceWeek | Promo2SinceYear | PromoInterval |
+--------------------------+--------+-----------------+-----------------+---------------+
|           2008           |   0    |        0        |        0        |               |
+--------------------------+--------+-----------------+-----------------+---------------+
+-------------+--------------+-----+
| StoreType.1 | Assortment.1 | ... |
+-------------+--------------+-----+
|      c      |      a       | ... |
+-------------+--------------+-----+
[1 rows x 30 columns]

+----+-------+-----------+------+-------+--------------+---------------+-----------+
| Id | Store | DayOfWeek | Open | Promo | StateHoliday | SchoolHoliday | StoreType |
+----+-------+-----------+------+-------+--------------+---------------+-----------+
| 1  |   1   |     4     |  1   |   1   |      0       |       0       |     c     |
+----+-------+-----------+------+-------+--------------+---------------+-----------+
+------------+---------------------+---------------------------+--------------------------+
| Assortment | CompetitionDistance | CompetitionOpenSinceMonth | CompetitionOpenSinceYear |
+------------+---------------------+---------------------------+--------------------------+
|     a      |         1270        |             9             |           2008           |
+------------+---------------------+---------------------------+--------------------------+
+--------+-----------------+-----------------+---------------+-------------+--------------+
| Promo2 | Promo2SinceWeek | Promo2SinceYear | PromoInterval | StoreType.1 | Assortment.1 |
+--------+-----------------+-----------------+---------------+-------------+--------------+
|   0    |        0        |        0        |               |      c      |      a       |
+--------+-----------------+-----------------+---------------+-------------+--------------+
+-----------------------+-----------------------------+-----+
| CompetitionDistance.1 | CompetitionOpenSinceMonth.1 | ... |
+-----------------------+-----------------------------+-----+
|          1270         |              9              | ... |
+-----------------------+-----------------------------+-----+
[1 rows x 28 columns]

In [36]:
# Convert store to a factor variable. In Graphlab, factor variables are automatically inferred from str variables
train['Store'] = train['Store'].astype(str)
test['Store'] = test['Store'].astype(str)

In [37]:
# create cross validation dataset from training dataset
train_eighty_percent, train_cv_twenty_percent = train.random_split(0.8, seed=1)

In [38]:
# Train the model on 80% of the training data
features = [ x for x in train.column_names() if x not in ["Id","Date","Sales", "logSales", "Customers"] ]
glm_model = graphlab.linear_regression.create(train_eighty_percent, target="logSales", features=features)

PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

PROGRESS: WARNING: Detected extremely low variance for feature(s) 'Open' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
PROGRESS: Linear regression:
PROGRESS: --------------------------------------------------------
PROGRESS: Number of examples          : 641963
PROGRESS: Number of features          : 27
PROGRESS: Number of unpacked features : 27
PROGRESS: Number of coefficients    : 1153
PROGRESS: Starting L-BFGS
PROGRESS: --------------------------------------------------------
PROGRESS: +-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+
PROGRESS: | Iteration | Passes   | Step size | Elapsed Time | Training-max_error | Validation-max_error | Training-rmse | Validation-rmse |
PROGRESS: +-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+
PROGRESS: | 1         | 6        | 0.000000  | 2.302898     | 6.567192           | 6.381633             | 2.158595      | 2.163897        |
PROGRESS: | 2         | 9        | 5.000000  | 3.687285     | 4.987398           | 4.551421             | 1.219232      | 1.224005        |
PROGRESS: | 3         | 10       | 5.000000  | 4.318884     | 12.721447          | 9.826279             | 6.154518      | 6.156661        |
PROGRESS: | 4         | 12       | 1.000000  | 5.408468     | 5.437631           | 4.355151             | 0.899068      | 0.906406        |
PROGRESS: | 5         | 13       | 1.000000  | 6.030935     | 5.432105           | 3.996120             | 0.825793      | 0.832389        |
PROGRESS: | 6         | 14       | 1.000000  | 6.663756     | 5.665220           | 3.645227             | 0.594772      | 0.597859        |
PROGRESS: | 10        | 18       | 1.000000  | 9.138755     | 5.066204           | 3.282844             | 0.343873      | 0.345167        |
PROGRESS: +-----------+----------+-----------+--------------+--------------------+----------------------+---------------+-----------------+

In [40]:
predictions_cv = glm_model.predict(train_cv_twenty_percent)
predictions_cv.head(5)
glm_model.evaluate(train_cv_twenty_percent)

{'max_error': 4.455697885074336, 'rmse': 0.34421533776756735}

In [45]:
boosted_model = graphlab.boosted_trees_regression.create(train_eighty_percent, target='logSales', 
                                                         features=features,
                                                         max_iterations=20, 
                                                         max_depth = 20)

PROGRESS: Creating a validation set from 5 percent of training data. This may take a while.
          You can set ``validation_set=None`` to disable validation tracking.

PROGRESS: WARNING: Detected extremely low variance for feature(s) 'Open' because all entries are nearly the same.
Proceeding with model training using all features. If the model does not provide results of adequate quality, exclude the above mentioned feature(s) from the input dataset.
PROGRESS: Boosted trees regression:
PROGRESS: --------------------------------------------------------
PROGRESS: Number of examples          : 641736
PROGRESS: Number of features          : 27
PROGRESS: Number of unpacked features : 27
PROGRESS: Starting Boosted Trees
PROGRESS: --------------------------------------------------------
PROGRESS:   Iter          RMSE          Elapsed time
PROGRESS:         (training) (validation)
PROGRESS:      0   5.793e+00   5.790e+00        6.48s
PROGRESS:      1   4.061e+00   4.059e+00       13.42s
PROGRESS:      2   2.849e+00   2.847e+00       20.97s
PROGRESS:      3   2.003e+00   2.001e+00       29.07s
PROGRESS:      4   1.413e+00   1.411e+00       37.42s
PROGRESS:      5   1.003e+00   1.002e+00       45.55s
PROGRESS:      6   7.195e-01   7.186e-01       53.66s
PROGRESS:      7   5.267e-01   5.263e-01       61.80s
PROGRESS:      8   3.992e-01   3.992e-01       70.39s
PROGRESS:      9   3.167e-01   3.180e-01       79.12s
PROGRESS:     10   2.674e-01   2.698e-01       87.98s
PROGRESS:     11   2.388e-01   2.419e-01       96.45s
PROGRESS:     12   2.222e-01   2.260e-01      104.97s
PROGRESS:     13   2.119e-01   2.161e-01      113.83s
PROGRESS:     14   2.064e-01   2.110e-01      121.37s
PROGRESS:     15   2.029e-01   2.076e-01      129.06s
PROGRESS:     16   1.994e-01   2.044e-01      136.64s
PROGRESS:     17   1.956e-01   2.012e-01      144.27s
PROGRESS:     18   1.940e-01   1.997e-01      151.70s
PROGRESS:     19   1.927e-01   1.984e-01      159.14s

In [46]:
boosted_predictions_cv = boosted_model.predict(train_cv_twenty_percent)
boosted_model.evaluate(train_cv_twenty_percent)

{'max_error': 4.289474639287425, 'rmse': 0.1994870250767679}

In [48]:
results_sales = boosted_model.predict(test)
results = graphlab.SFrame({'Id': test['Id'], 'Sales': results_sales})
results['Sales'] = results['Sales'].apply(lambda x: math.exp(x))
results

Columns:
	Id	int
	Sales	float

Rows: 41088

Data:
+----+---------------+
| Id |     Sales     |
+----+---------------+
| 1  | 5206.38934588 |
| 2  |  6978.5341929 |
| 3  | 7887.44704009 |
| 4  | 6899.22268636 |
| 5  | 7597.93885814 |
| 6  | 6776.81744489 |
| 7  |  7597.1358328 |
| 8  | 7485.32176831 |
| 9  | 6415.41946468 |
| 10 | 6390.82390905 |
+----+---------------+
[41088 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [49]:
 results.save('result6_graphlab_log_boostedTrees.csv', format='csv')